contact/urls.py
from django.urls import path
from . import views



app_name = 'contact'

urlpatterns = [ 
    path('',views.send_message,name='contact'),

   
]

home/urls.py
from django.urls import path
from . import views

####################
app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),

]

jobs/urls.py
from django.urls import path
from . import views

####################
app_name = 'jobs'

urlpatterns = [
    path('',views.job_list,name='job_list'),

    path('<str:slug>/',views.job_detail,name='job_detail'),
    path('apply_job/<str:slug>/',views.apply_job,name='apply_job'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/',include('jobs.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/',include('contact.urls',namespace='contact')),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from jobs.models import Job
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    index = Job.objects.all()
    paginator = Paginator(index,6)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    context = {'jobs':index,'pag':page_object}
    return render(request,'home/index.html',context)

templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
   
   <!-- ***** Preloader End ***** -->

    <!-- Header -->


    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text">
      <div class="container-fluid">
        <div class="owl-banner owl-carousel">
          {% for job in jobs %}
          <div class="item">
            <img src="{{job.image.url}}" alt="">
            <div class="item-content">
              
              <div class="main-content">
                <div class="meta-category">
                  <span>${{job.salary}}</span>
                </div>

                <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job.title}}</h4></a>

                <ul class="post-info">
                  
                </ul>
              </div>
            
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <section class="blog-posts grid-system">
      <div class="container">
        <div class="all-blog-posts">
          <h2 class="text-center">Featured Jobs</h2>
          <br>
          
          <div class="row">
            {% for job in pag %}
            <div class="col-md-4 col-sm-6">
              
              <div class="blog-post">
                <div class="blog-thumb">
                  <img src="" alt="">
                </div>
                <div class="down-content">
                  <span>${{job.salary}}</span>
                  <a href="{% url 'jobs:job_list' %}"><h4>{{job.title}}</h4></a>
                  <p>{{job.content}}</p>
                  <div class="post-options">
                    <div class="row">
                      <div class="col-lg-12">
                        <ul class="post-tags">
                          <li><i class="fa fa-bullseye"></i></li>
                          <li><a href="{% url 'jobs:job_detail' job.slug %}">View Job</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
            </div>
            {% endfor %}
          </div>
          
        </div>
      </div>
    </section>

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>contact us </span>
                  <h4>If you need a help</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a href="{% url 'contact:contact' %}">Contact Us</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>





    <!-- Bootstrap core JavaScript -->
{% endblock body %}