home/urls.py
from django.urls import path
from . import views

####################
app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),

]

jobs/urls.py
from django.urls import path
from . import views

####################
app_name = 'jobs'

urlpatterns = [
    path('',views.job_list,name='job_list'),

    path('<str:slug>/',views.job_detail,name='job_detail'),
    path('apply_job/<str:slug>/',views.apply_job,name='apply_job'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/',include('jobs.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/',include('contact.urls',namespace='contact')),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

jobs/models.py
from datetime import datetime
from distutils.command.upload import upload
from email.policy import default
from random import choices
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.




class Job(models.Model):
    title = models.CharField(max_length=150,default='')
    salary = models.IntegerField(default=500)
    location = models.CharField(default='',max_length=150)
    image = models.ImageField(upload_to='photos/%y/%m/%d')
    created_at = models.DateTimeField(default=datetime.now)
    description = models.TextField(default='')
    content = models.CharField(max_length=75,null=True,blank=True) 
    slug = models.CharField(max_length=750,null=True,blank=True) 

    def save(self,*args,**kwargs):
        self.slug =slugify(self.title) 
        self.content = self.description
        super(Job,self).save(*args,**kwargs)



    def __str__(self):
        return self.title


Gender =[ 
    ('male','male'),
    ('female','female')
    ]

class Apply(models.Model):
    user =models.ForeignKey(User,related_name='job_apply',on_delete=models.CASCADE)
    job = models.ForeignKey('Job', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=50, choices=Gender)
    country = models.CharField(max_length=100)
    email = models.EmailField(max_length=250)
    cv = models.FileField(upload_to='cv/%y/%m/%d')
    your_skills = models.TextField(default='')
    date_and_time = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.name

jobs/forms.py
from dataclasses import fields

from django import forms
from .models import Apply


class ApplyForm(forms.ModelForm):
    class Meta:
        model = Apply
        fields = '__all__'
        exclude = ('user','date_and_time')

jobs/views.py
from contextlib import redirect_stderr
from django.shortcuts import render
from .models import Job
from .filters import JobFilter
from django.core.paginator import Paginator
from .forms import ApplyForm
from contact.models import Info

# Create your views here.

#for all jobs
def job_list(request):
    job_list = Job.objects.all()

    #filter 
    myfilter = JobFilter(request.GET , queryset=job_list)
    job_list = myfilter.qs

    #paginator
    paginator = Paginator(job_list,4)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    context = {'jobs':page_object,'myfilter':myfilter} 
    return render(request,'job/job_list.html',context)    




#for one job or detail
def job_detail(request,slug):
    job_detail = Job.objects.get(slug=slug)

#contact detail
    info = Info.objects.all()    

    context = {'job':job_detail,'info':info}
    return render(request,'job/job_detail.html',context)

def apply_job(request,slug):
    job_detail = Job.objects.get(slug=slug)

    #apply for a job

    if request.method=='POST':
        form = ApplyForm(request.POST,request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.job = job_detail
            myform.save()
            print('doo00ne')      

    else :
        form = ApplyForm()

    context = {'form1':form}
    return render(request,'job/apply_job.html',context)    

def index(request):
    return render(request,'home/index.html')

templates/job/apply_job.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}
<br>
<br>
<br>
<br>
<br>
<div class="col-lg-8 mx-auto">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form1 %}
      {% buttons %}
        
        <input class="boxed-btn3 w-100 mt-3" type="submit" value="Apply for this Job">
      {% endbuttons %}
  </form>
</div>

{% endblock body %}

templates/job/job_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
      <!-- Page Content -->
      <!-- Banner Starts Here -->
      <div class="heading-page header-text">
        <section class="page-heading">
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="text-content">
                  
                  <h4>${{job.salary}}</h4>
                  <h2>{{job.title}}</h2>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      
      <!-- Banner Ends Here -->

      <section class="blog-posts grid-system">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div>
                <img src="{{job.image.url}}" alt="" class="img-fluid wc-image">
              </div>

              <br>
            </div>

            <div class="col-md-8">
              <div class="sidebar-item recent-posts">
                <div class="sidebar-heading">
                  <h2>
                  <i class="fa fa-map-marker"></i> {{job.location}} &nbsp;&nbsp;
                  <i class="fa fa-calendar"></i>{{job.published_at|date:'d M o'}} &nbsp;&nbsp;
                  
                  </h2>
                </div>

                <div class="content">
                  <p>{{job.content}}</p>
                </div>
              </div>

              <br>
            
              <div class="row">
                <div class="col-sm-4">
                  <div class="main-button">
                    <a href="{% url 'jobs:apply_job' job.slug %}">Apply for this Job</a>
                  </div>
                </div>
              </div>

              <br>
            </div>
          </div>
        </div>
      </section>

      <div class="section contact-us">
        
        <hr >
          <div class="row">
            <div class="col-md-8 ">
              <div class="sidebar-heading p-2">
                <h2>Description</h2>

              </div>
              <div class="content p-2">
                <p>{{job.description}}</p>
              
              </div>
              
            </div>

            <div class="col-lg-4">
              <div class="sidebar-item recent-posts">
                <div class="sidebar-heading">
                  <h2>Contact Details</h2>
                </div>

                
                {% for info in info %}
                <div class="content">
                  <p>
                    <span>Name</span>

                    <br>

                    <strong><h4>{{info.name}}</h4></strong>
                  </p>

                  <p>
                    <span>Phone</span>

                    <br>
                    
                    <strong>
                      <a href="tel:{{info.phone_number}}">{{info.phone_number}}</a>
                    </strong>
                  </p>



                  <p>
                    <span>Email</span>

                    <br>
                    
                    <strong>
                      <a href="mailto:{{info.email}}">{{info.email}}</a>
                    </strong>
                  </p>

                  <p>
                    <span>location</span>

                    <br>
                    
                    <strong>
                      <h5>{{info.location}}</h5>
                    </strong>
                  </p>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>

          
        </div>
      </div>


{% endblock body %}

templates/job/job_list.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>PHPJabbers.com | Free Job Agency Website Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
{% include 'header.html' %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>{{ jobs.paginator.count }}+ Jobs Available</h4>
                <h2>Choose the perfect job!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="blog-posts grid-system">
      <div class="container">
        <div class="all-blog-posts">
          <div class="row">
            <div class="col-md-4 col-xs-12">
              <div><h4>Filters</h4></div>
              <br>
               <form method="GET">
                    {% bootstrap_form myfilter.form %}
                    
                    <input class="boxed-btn3 w-100 mt-3" type="submit" value="Filter">
                </form>
            </div>
          
            <div class="col-md-8 col-xs-12">
              <div class="row">
                {% for job in jobs %}
                <div class="col-sm-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      
                      <a href="{% url 'jobs:job_detail' job.slug %}"><img src="{{job.image.url}}" alt=""></a>
                    </div>
                    <div class="down-content">
                      <span>${{job.salary}}</span>
                      <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job.title}}</h4></a>
                      <p>{{job.description}}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-bullseye"></i></li>
                              <li><a href="{% url 'jobs:job_detail' job.slug %}">View Job</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
            
                </div>  
                {% endfor %}         
              </div>
            </div>
            <br>
            
               {% if jobs.has_other_pages %}
            
                <div class="col-lg-12">
                    
                     <ul class="page-numbers">
                         {% if jobs.has_previous %}
                         <li><a href="?page={{jobs.previous_page_number}}"><i class="fa fa-angle-double-left"></i></a></li>
                         {% endif %}
                         
                         {% for i in jobs.paginator.page_range %}
                         <li><a href="?page={{i}}">{{i}}</a></li>
                         {% endfor %}
                         
                         {% if jobs.has_next %}
                         <li><a href="?page={{jobs.next_page_number}}"><i class="fa fa-angle-double-right"></i></a></li>
                         {% endif %}
                     </ul>
                </div>
            
               {% endif %}
               </div>
           </div>
          <!-- </div>
          <div class="col-lg-12">
               {% if jobs.has_other_pages %}
               <ul class="page-numbers">

                    {% if jobs.has_previous %}
                    <li><a href="?page={{jobs.previous_page_number}}"><i class="fa fa-angle-double-left"></i></a></li>
                    {% endif %}
                    
                    {% for i in jobs.paginator.page_range %}
                    <li><a href="?page={{i}}">1</a></li>
                    {% endfor %}

                    {% if jobs.has_next %}
                    <li><a href="?page={{jobs.next_page_number}}"><i class="fa fa-angle-double-right"></i></a></li>
                    {% endif %}

                </ul>
               {% endif %}
             </div> -->
          
        </div>
      </div>
    </section>

    
{% include 'footer.html' %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js'%}" ></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>

    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

  </body>
</html>

templates/job/jobs.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Jobs</h4>
                <h2>Choose the perfect job!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="blog-posts grid-system">
      <div class="container">
        <div class="all-blog-posts">
          <div class="row">
            <div class="col-md-4 col-xs-12">
                <form action="#">
                 <h4 style="margin-bottom: 15px">Type</h4>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Contract (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Full time (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Internship (5)</span>
                      </label>
                 </div>

                 <br>

                 <h4 style="margin-bottom: 15px">Category</h4>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Accounting / Finance / Insurance Jobs (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Accounting / Finance / Insurance Jobs (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Accounting / Finance / Insurance Jobs (5)</span>
                      </label>
                 </div>

                 <br>

                 <h4 style="margin-bottom: 15px">Career levels</h4>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Entry Level (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Entry Level (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Entry Level (5)</span>
                      </label>
                 </div>

                 <br>

                 <h4 style="margin-bottom: 15px">Education levels</h4>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Associate Degree (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Associate Degree (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                           <span>Associate Degree (5)</span>
                      </label>
                 </div>

                 <br>


                 <h4 style="margin-bottom: 15px">Years of experience</h4>

                 <div>
                      <label>
                           <input type="checkbox">

                            <span>&lt; 1 (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                            <span>&lt; 1 (5)</span>
                      </label>
                 </div>

                 <div>
                      <label>
                           <input type="checkbox">

                            <span>&lt; 1 (5)</span>
                      </label>
                 </div>
                </form>
            </div>

            <div class="col-md-8 col-xs-12">
              <div class="row">
                <div class="col-sm-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/product-1-720x480.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>$60 000</span>
                      <a href="job-details.html"><h4>Lorem ipsum dolor sit amet, consectetur</h4></a>
                      <p>Nullam nibh mi, tincidunt sed sapien ut, rutrum hendrerit velit. Integer auctor a mauris sit amet eleifend.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-bullseye"></i></li>
                              <li><a href="job-details.html">View Job</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/product-2-720x480.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>$60 000</span>
                      <a href="job-details.html"><h4>Lorem ipsum dolor sit amet, consectetur</h4></a>
                      <p>Nullam nibh mi, tincidunt sed sapien ut, rutrum hendrerit velit. Integer auctor a mauris sit amet eleifend.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-bullseye"></i></li>
                              <li><a href="job-details.html">View Job</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/product-3-720x480.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>$60 000</span>
                      <a href="job-details.html"><h4>Lorem ipsum dolor sit amet, consectetur</h4></a>
                      <p>Nullam nibh mi, tincidunt sed sapien ut, rutrum hendrerit velit. Integer auctor a mauris sit amet eleifend.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-bullseye"></i></li>
                              <li><a href="job-details.html">View Job</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/product-4-720x480.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>$60 000</span>
                      <a href="job-details.html"><h4>Lorem ipsum dolor sit amet, consectetur</h4></a>
                      <p>Nullam nibh mi, tincidunt sed sapien ut, rutrum hendrerit velit. Integer auctor a mauris sit amet eleifend.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-bullseye"></i></li>
                              <li><a href="job-details.html">View Job</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/product-5-720x480.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>$60 000</span>
                      <a href="job-details.html"><h4>Lorem ipsum dolor sit amet, consectetur</h4></a>
                      <p>Nullam nibh mi, tincidunt sed sapien ut, rutrum hendrerit velit. Integer auctor a mauris sit amet eleifend.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-bullseye"></i></li>
                              <li><a href="job-details.html">View Job</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/product-6-720x480.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>$60 000</span>
                      <a href="job-details.html"><h4>Lorem ipsum dolor sit amet, consectetur</h4></a>
                      <p>Nullam nibh mi, tincidunt sed sapien ut, rutrum hendrerit velit. Integer auctor a mauris sit amet eleifend.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-bullseye"></i></li>
                              <li><a href="job-details.html">View Job</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          
        </div>
      </div>
    </section>

{% endblock body %}