accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'

urlpatterns = [ 
    path('signup/',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('profile/edit',views.edit_profile,name='profile_edit'),
   
   
]

home/urls.py
from django.urls import path
from . import views

####################
app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/',include('jobs.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/',include('contact.urls',namespace='contact')),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from distutils.command.upload import upload
from email.policy import default
import imp
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,related_name ='signup',on_delete=models.CASCADE)
    location = models.CharField(max_length=100,default='')
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to='profile_photos/%y/%m/%d',default='/photos/22/10/03/images.jpg')

    def __str__(self) :
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile



class SignForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['location','image','phone_number']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login
from django.shortcuts import render,redirect
from .forms import ProfileForm, SignForm, UserForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.urls import reverse
# Create your views here.
def signup(request):

    if request.method=='POST':
        form = SignForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)#يعني تروح للداتا تشوف هل في يوزر وباس بنفس المعطيات دي لو فيه اعمل تسجيل دخول
            login(request,user)
            return redirect('/accounts/profile')
    else :
        form = SignForm() 

    return render(request,'registration/signup.html',{'form':form})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    context = {'profile':profile}

    return render(request,'accounts/profile.html',context)



def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    if request.method=='POST':
        userform=UserForm(request.POST,instance=request.user)
        profileForm = ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid():
            userform.save()
            profileForm = profileForm.save(commit=False)
            profileForm.user = request.user
            profileForm.save()
            return redirect(reverse('accounts:profile'))

    else :
        userform=UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)
        context = {'userform':userform,'profileform':profileform}

    return render(request,'accounts/edit_profile.html',context)

accounts/templates/accounts/edit_profile.html
{% extends 'base_generic.html' %}
{% load bootstrap4 %}

{% block content %}
<br>
<br>
<br>
<br>
<br>

    <!-- header-end -->

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Edit Your Profile </h3>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <br>
    <br>

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto"> 
                    
                    
                    <div class="apply_job_form white-bg">
                      
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}

                            
                            <input class="boxed-btn3 w-100" type="submit" value="Save">
                            
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
{% endblock %}
   

accounts/templates/accounts/profile.html
{% extends 'base_generic.html' %}
{% load bootstrap4 %}

{% block content %}
    <!-- header-end -->





<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


  <div class="card p-4">
    <div class=" image d-flex flex-column justify-content-center align-items-center mx-auto ">
       <img src="{{profile.image.url}}" height="100" width="100" />
      <span class="name mt-3"><h4>{{profile.user}}</h4> </span>
      <span class="idd"><h5>{{profile.user.email}}</h5></span>
  
      <div class="d-flex flex-row justify-content-center align-items-center mt-3">
        <span class="follow"><h6>Your Phone :</h6><span class="number"><h6>{{profile.phone_number}}</h6></span>  </span>
      </div>
      <div class="p-4">
        <a href="{% url 'accounts:profile_edit' %}" class="boxed-btn3 w-100">Edit Profile</a>
      </div>
      <!-- <div class="btn btn-secondary">
        <button class="btn1 btn-dark" href="{% url 'accounts:profile_edit' %}">Edit Profile</button>
      </div> -->
    </div>

<br>
<br>
<br>
<br>
{% endblock %}