about/urls.py
from django.urls import path
from . import views

####################
app_name = 'about'

urlpatterns = [
    path('',views.about,name='about'),

]

accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'

urlpatterns = [ 
    path('signup/',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('profile/edit',views.edit_profile,name='profile_edit'),
   
   
]

contact/urls.py
from django.urls import path
from . import views



app_name = 'contact'

urlpatterns = [ 
    path('',views.send_message,name='contact'),

   
]

home/urls.py
from django.urls import path
from . import views

####################
app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),

]

jobs/urls.py
from django.urls import path
from . import views

####################
app_name = 'jobs'

urlpatterns = [
    path('',views.job_list,name='job_list'),

    path('<str:slug>/',views.job_detail,name='job_detail'),
    path('apply_job/<str:slug>/',views.apply_job,name='apply_job'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/',include('jobs.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/',include('contact.urls',namespace='contact')),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>PHPJabbers.com | Free Job Agency Website Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  

    {% include 'header.html' %}
    {% block body %}


    {% endblock body %}
    {% include 'footer.html' %}


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js'%}" ></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>

    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

  </body>
</html>

templates/base_generic.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>PHPJabbers.com | Free Job Agency Website Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  

    {% include 'header.html' %}
    {% block content %}


    {% endblock content %}
    {% include 'footer.html' %}


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js'%}" ></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>

    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

  </body>
</html>

templates/footer.html
    <footer>
        <div class="container">
        <div class="row">
            <div class="col-lg-12 ">
            <ul class="social-icons">
                <li><a href="#">Facebook</a></li>
                <li><a href="https://twitter.com/AhmedHa13707652?t=qSwlKPo98ru8wkNAxE2DEA&s=09">Twitter</a></li>
                <li><a href="https://www.linkedin.com/in/ahmed-hamdy-93a390217">Linkedin</a></li>
            </ul>
            </div>
            <div class="col-lg-12">
            <div class="copyright-text">
                <p>
                Copyright © 2020 Company Name
                | Template by: <a href="https://www.phpjabbers.com/">PHPJabbers.com</a>
                </p>
            </div>
            </div>
        </div>
        </div>
    </footer>

templates/header.html
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
        <nav class="navbar navbar-expand-lg">
          <div class="container">
            <a class="navbar-brand" href="{% url 'home:index' %}"><h2>Job Agency Website<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:index' %}">Home
                    <span class="sr-only">(current)</span>
                  </a>
                </li> 
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'jobs:job_list' %}">Jobs</a>
                </li>
  
                <li class="nav-item dropdown">
                    
                    <div class="nav-item">
                      <a class="nav-link" href="{% url 'about:about' %}">About Us</a>
 
                    </div>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'contact:contact' %}">Contact Us</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:profile'%}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout'%}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login'%}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </header>

      